include "application.conf"

app {
  pvwattsApiKey = ${?PVWATTS_API_KEY}
  serverPort = ${?SERVER_PORT}
  redis {
    url = ${REDIS_URL}
    username = ${?REDIS_USERNAME}
    password = ${?REDIS_PASSWORD}
  }
  db {
    url = ${DB_URL}
    user = ${DB_USER}
    password = ${DB_PASSWORD}
  }
  jwt {
    secret = ${JWT_SECRET}
    issuer = ${?JWT_ISSUER}
    audience = ${?JWT_AUDIENCE}
    realm = ${?JWT_REALM}
    expiryMinutes = ${?JWT_EXPIRY_MINUTES}
  }
}
