include "application.conf"

app {
  pvwattsApiKey = ${?PVWATTS_API_KEY}
  serverPort = ${?SERVER_PORT}
  redisUrl = ${REDIS_URL}
  redisUsername = ${?REDIS_USERNAME}
  redisPassword = ${?REDIS_PASSWORD}
}
