ktor {
  deployment {
    port = 8080
    port = ${?SERVER_PORT}
    host = "0.0.0.0"
  }
  application {
    modules = [ com.devtamuno.heliocore.ApplicationKt.module ]
  }
}

app {
  pvwattsApiKey = ${?PVWATTS_API_KEY}
  serverPort = ${?SERVER_PORT}
  redis {
    url = "redis://localhost:6379"
    username = ""
    password = "aGVsaW8tcmVkaXMtZGV2"
  }
  db {
    url = "jdbc:postgresql://localhost:5432/heliocore"
    user = "heliocore"
    password = "aGVsaW8tcmVkaXMtZGV2"
  }
  jwt {
    secret = "aGVsaW8tcmVkaXMtZGV2qIsxc"
    issuer = "helio-core"
    audience = "helio-core-users"
    realm = "helio-core"
    expiryMinutes = 60
    refreshExpiryDays = 30
  }
}
