ktor {
  deployment {
    port = 8080
    port = ${?SERVER_PORT}
    host = "0.0.0.0"
  }
  application {
    modules = [ com.devtamuno.heliocore.ApplicationKt.module ]
  }
}

app {
  pvwattsApiKey = ${?PVWATTS_API_KEY}
  serverPort = ${?SERVER_PORT}
  redisUrl = "redis://localhost:6379"
  redisUsername = ""
  redisPassword = "aGVsaW8tcmVkaXMtZGV2"
}
